"""
parser.py
---------
Converts a raw transcript .txt file into a structured list of "turns".

Design decision:
This is the single most important file for hallucination-prevention.
Every timestamp and every quote shown later in the app is read directly
from these structured turns -- never generated by the LLM. The LLM only
ever *selects* a substring from a turn's text; it never invents a
timestamp or types out a quote from memory.

Expected transcript format (as given in the case pack):

    Expert 1 – Dr. Jean Martin
    Role: Head of Urology
    Market: France

    00:00
    Interviewer: Thanks for joining...

    00:18
    Dr. Martin: Adoption is growing...
"""
import re
import os
from dataclasses import dataclass, asdict
from typing import List, Optional

TIMESTAMP_RE = re.compile(r"^(\d{1,2}:\d{2})\s*$")
SPEAKER_LINE_RE = re.compile(r"^([^:]+):\s*(.*)$")


@dataclass
class Turn:
    transcript_id: str      # e.g. "Transcript_1_France"
    expert_name: str
    role: str
    market: str
    turn_index: int          # order within the transcript
    timestamp: str           # "MM:SS" as it appears in the source
    speaker: str             # "Interviewer" or the expert's name as printed
    text: str                # verbatim text of this turn
    is_interviewer: bool

    def to_dict(self):
        return asdict(self)

    def citation(self) -> str:
        """Human readable citation string, e.g. 'Dr. Jean Martin, France, 02:18'"""
        return f"{self.expert_name} ({self.market}, {self.timestamp})"


def parse_transcript(filepath: str) -> List[Turn]:
    transcript_id = os.path.splitext(os.path.basename(filepath))[0]

    with open(filepath, "r", encoding="utf-8") as f:
        raw_lines = [l.rstrip("\n") for l in f]

    # --- Parse header metadata (before the first timestamp line) ---
    expert_name, role, market = "Unknown Expert", "Unknown Role", "Unknown Market"
    header_end = 0
    for i, line in enumerate(raw_lines):
        if TIMESTAMP_RE.match(line.strip()):
            header_end = i
            break
        stripped = line.strip()
        if stripped.lower().startswith("role:"):
            role = stripped.split(":", 1)[1].strip()
        elif stripped.lower().startswith("market:"):
            market = stripped.split(":", 1)[1].strip()
        elif stripped and "–" in stripped or (stripped and "-" in stripped and "Expert" in stripped):
            # e.g. "Expert 1 – Dr. Jean Martin"
            parts = re.split(r"[–-]", stripped, maxsplit=1)
            if len(parts) == 2:
                expert_name = parts[1].strip()

    # --- Parse body: timestamp line, then one speaker:text line (may wrap) ---
    turns: List[Turn] = []
    i = header_end
    turn_index = 0
    n = len(raw_lines)
    while i < n:
        line = raw_lines[i].strip()
        ts_match = TIMESTAMP_RE.match(line)
        if ts_match:
            timestamp = ts_match.group(1)
            i += 1
            # collect following non-blank lines until next timestamp or EOF
            content_lines = []
            while i < n and not TIMESTAMP_RE.match(raw_lines[i].strip()) and raw_lines[i].strip() != "":
                content_lines.append(raw_lines[i].strip())
                i += 1
            content = " ".join(content_lines).strip()
            speaker, text = _split_speaker(content)
            if text:
                is_interviewer = speaker.lower().startswith("interview")
                turns.append(
                    Turn(
                        transcript_id=transcript_id,
                        expert_name=expert_name,
                        role=role,
                        market=market,
                        turn_index=turn_index,
                        timestamp=timestamp,
                        speaker=speaker,
                        text=text,
                        is_interviewer=is_interviewer,
                    )
                )
                turn_index += 1
        else:
            i += 1

    return turns


def _split_speaker(content: str):
    m = SPEAKER_LINE_RE.match(content)
    if m:
        return m.group(1).strip(), m.group(2).strip()
    return "Unknown", content


def parse_interview_guide(filepath: str) -> List[str]:
    """Extract numbered questions from the interview guide text file."""
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()
    questions = []
    for line in text.splitlines():
        line = line.strip()
        m = re.match(r"^\d+\.\s*(.+)$", line)
        if m:
            questions.append(m.group(1).strip())
    return questions


if __name__ == "__main__":
    # quick manual check
    import json
    for fname in ["Transcript_1_France.txt", "Transcript_2_Germany.txt", "Transcript_3_UK.txt"]:
        turns = parse_transcript(os.path.join(os.path.dirname(__file__), "..", "data", fname))
        print(f"\n--- {fname}: {len(turns)} turns ---")
        for t in turns[:3]:
            print(json.dumps(t.to_dict(), indent=2))
    qs = parse_interview_guide(os.path.join(os.path.dirname(__file__), "..", "data", "Interview_Guide.txt"))
    print("\nQuestions:", qs)
